# Generated by Django 4.0.5 on 2022-06-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neighbourhood', '0007_alter_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(max_length=130),
        ),
    ]
